version: '3.8'

services:
  app:
    build:
      context: .  # Use current directory as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile name (optional if named "Dockerfile")
    container_name: grocery_store_container
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/grocerystore
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=swapy
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: grocerystore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: swapy
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  postgres_data:
